jji: Improve error messages

diff --git a/extra/jji b/extra/jji
--- a/extra/jji
+++ b/extra/jji
@@ -10,11 +10,19 @@
 # channel argument, switches to the previously set channel.  The shorter
 # `/chan`or `/c` can also be used.
 
-: "${1:?Missing channel argument}"
-
+arg0=${0##*/}
 fifo=${IRC_DIR:-$HOME/irc}/${IRC_HOST:-irc.freenode.org}/in
-[ -p "$fifo" ] && [ -w "$fifo" ] ||
+
+! [ "$1" ] && {
+	printf '%s: missing channel argument\n' "$arg0" >&2
 	exit 1
+}
+
+if ! [ -p "$fifo" ] || ! [ -w "$fifo" ]; then
+	printf '%s: not a named pipe or not writeable: %s\n' \
+		"$arg0" "$fifo" >&2
+	exit 1
+fi
 
 chan=$1
 last_chan=$1
